language: python

matrix:
  include:
    - python: "2.7"
      env: PROJECT=idaplugin
    - python: "2.7"
      env: PROJECT=server DJANGO_SETTINGS_MODULE='rematch.settings.debug'
      services:
        - mysql
        - rabbitmq
    - python: "3.5"
      env: PROJECT=server DJANGO_SETTINGS_MODULE='rematch.settings.production'
      services:
        - mysql
        - rabbitmq
    - python: "2.7"
      env: PROJECT=server DJANGO_SETTINGS_MODULE='rematch.settings.docker' ENV=docker
      services: docker
    - python: "2.7"
      env: PROJECT=setup.py
    - python: "3.6"
      env: PROJECT=setup.py

branches:
  only:
    - master

# Handle git submodules ourselves to replace ssh login with https login
git:
    submodules: false
# Use sed to replace the SSH URL with the public URL, then initialize submodules
before_install:
    - sed -i 's/git@github.com:/https:\/\/github.com\//' .gitmodules
    - git submodule update --init --recursive

install:
  - set +vx;
  - pip install --upgrade pip setuptools wheel
  - if [ "${ENV}" = "docker" ]; then
      service docker start ;
      docker-compose -f ./${PROJECT}/docker-compose.yml build ;
      docker-compose -f ./${PROJECT}/docker-compose.yml up -d ;
      if [ -f ./tests/${PROJECT}/requirements.txt ]; then
        docker-compose -f ./${PROJECT}/docker-compose.yml exec web pip install -r ./tests/requirements.txt ;
      fi ;
    else
      if [ "${PROJECT}" = "idaplugin" ]; then
        wget https://repo.continuum.io/miniconda/Miniconda2-latest-Linux-x86_64.sh -O miniconda.sh;
        bash ./miniconda.sh -b -p "${HOME}/miniconda";
        export PATH=${HOME}/miniconda/bin:$PATH;
        conda info -a;
        conda install --yes python=${TRAVIS_PYTHON_VERSION} pyqt;
      else
        pip install --only-binary=numpy,scipy numpy scipy ;
      fi ;

      if [ -f tests/${PROJECT}/requirements.txt ]; then
        pip install -r tests/${PROJECT}/requirements.txt ;
      fi ;
      if [ -f "${PROJECT}/requirements.txt" ]; then
        pip install -r "${PROJECT}/requirements.txt" ;
      fi ;
    fi ;
  - pip install flake8 coveralls pytest-cov ;

script:
  - flake8 ./${PROJECT} --show-source --statistics
  - if [ -d ./tests/${PROJECT} ]; then flake8 ./tests/${PROJECT} --show-source ; fi ;
  - if [ -d ./tests/${PROJECT} ]; then
      if [ "${ENV}" = "docker" ]; then
        docker-compose -f ./${PROJECT}/docker-compose.yml exec web py.test ./ --verbose ;
      else
        PYTHONPATH=. py.test ./${PROJECT} ./tests/${PROJECT} --verbose --cov-report= --cov=$PROJECT ;
      fi ;
    fi ;
  - if [ "${PROJECT}" = "setup.py" ]; then python ./setup.py server install ; fi ;
  - if [ "${PROJECT}" = "setup.py" ]; then python ./setup.py idaplugin install ; fi ;

after_script:
  - if [ -d ./tests/${PROJECT} ] && [ "${ENV}" != "docker" ]; then
      coveralls ;
    fi ;
