services:
  - mysql

language: python
python:
  - "2.7"
  - "3.4"
  - "3.5"
env:
  - PROJECT=idaplugin
  - PROJECT=server
matrix:
  # idaplugin is run with python2.7, we'll check against python3 to assert compatibility
  exclude:
    - python: "3.4"
      env: PROJECT=idaplugin

branches:
  only: 
    - master

# Handle git submodules ourselves to replace ssh login with https login
git:
    submodules: false
# Use sed to replace the SSH URL with the public URL, then initialize submodules
before_install:
    - sed -i 's/git@github.com:/https:\/\/github.com\//' .gitmodules
    - git submodule update --init --recursive

install:
  - if [ ${PROJECT} = "server" ]; then
      set +vx;
      if [[ "$TRAVIS_PYTHON_VERSION" == "2.7" ]]; then
        wget https://repo.continuum.io/miniconda/Miniconda2-latest-Linux-x86_64.sh -O miniconda.sh;
      else
        wget https://repo.continuum.io/miniconda/Miniconda3-latest-Linux-x86_64.sh -O miniconda.sh;
      fi;
      bash ./miniconda.sh -b -p ${HOME}/miniconda;
      export PATH=${HOME}/miniconda/bin:$PATH;
      conda info -a;
      conda update --yes conda;
      conda install --yes python=${TRAVIS_PYTHON_VERSION} atlas numpy scipy scikit-learn;
    fi;
  - if [ -f ${PROJECT}/requirements.txt ]; then pip install -r ${PROJECT}/requirements.txt ; fi
  - if [ -f tests/requirements.txt ]; then pip install -r tests/requirements.txt ; fi
  - pip install flake8

before_script:
  - if [ ${PROJECT} = "server" ]; then
      mysql -e 'SHOW VARIABLES LIKE "%version%";' ;
    fi;

script:
  - flake8 ./${PROJECT} --show-source --statistics
  - if [ -d ./tests/${PROJECT} ]; then flake8 ./tests/${PROJECT} --verbose ; fi
  - if [ -d ./tests/${PROJECT} ]; then py.test ./${PROJECT} ./tests/${PROJECT} --verbose ; fi
    
