language: python

matrix:
  include:
    - python: "2.7"
      env: PROJECT=idaplugin ENV=conda
    - python: "2.7"
      env: PROJECT=server ENV=data DJANGO_SETTINGS_MODULE='rematch.settings.debug'
      services:
        - mysql
        - rabbitmq
    - python: "3.5"
      env: PROJECT=server ENV=data DJANGO_SETTINGS_MODULE='rematch.settings.production'
      services:
        - mysql
        - rabbitmq
    - python: "2.7"
      env: PROJECT=server ENV=docker DJANGO_SETTINGS_MODULE='rematch.settings.docker'
      services: docker
    - python: "2.7"
      env: PROJECT=setup.py
    - python: "3.6"
      env: PROJECT=setup.py
    - python: "3.6"
      env: PROJECT=docs
    - python: 2.7
      env: PROJECT=interop ENV=conda DJANGO_SETTINGS_MODULE='rematch.settings.debug'

branches:
  only:
    - master

# Handle git submodules ourselves to replace ssh login with https login
git:
    submodules: false
# Use sed to replace the SSH URL with the public URL, then initialize submodules
before_install:
    - sed -i 's/git@github.com:/https:\/\/github.com\//' .gitmodules
    - git submodule update --init --recursive

install:
  - set +vx;
  - pip install --upgrade pip setuptools wheel
  - if [ "${ENV}" = "docker" ]; then
      service docker start ;
      docker-compose -f ./${PROJECT}/docker-compose.yml build ;
      docker-compose -f ./${PROJECT}/docker-compose.yml up -d ;
      if [ -f ./tests/${PROJECT}/requirements.txt ]; then
        docker-compose -f ./${PROJECT}/docker-compose.yml exec web pip install -r ./tests/server/requirements.txt ;
      fi ;
      docker-compose -f ./${PROJECT}/docker-compose.yml exec web pip install coveralls pytest-cov ;
      pip install flake8 ;
    fi ;
  - if [ "${ENV}" = "conda" ]; then
      wget https://repo.continuum.io/miniconda/Miniconda2-latest-Linux-x86_64.sh -O miniconda.sh ;
      bash ./miniconda.sh -b -p "${HOME}/miniconda" ;
      export PATH=${HOME}/miniconda/bin:$PATH ;
      conda info -a ;
      conda install --yes python=${TRAVIS_PYTHON_VERSION} pyqt ;
    fi ;
  - if [ "${ENV}" = "data" ]; then
      pip install --only-binary=numpy,scipy numpy scipy ;
    fi ;
  - if [ "${ENV}" != "docker" ]; then
      if [ -f "tests/${PROJECT}/requirements.txt" ]; then
        pip install -r "tests/${PROJECT}/requirements.txt" ;
      fi ;
      if [ -f "${PROJECT}/requirements.txt" ]; then
        pip install -r "${PROJECT}/requirements.txt" ;
      fi ;
      pip install flake8 coveralls pytest-cov ;
    fi ;

script:
  - flake8 ./${PROJECT} --show-source --statistics
  - if [ -d ./tests/${PROJECT} ]; then flake8 ./tests/${PROJECT} --show-source ; fi ;
  - if [ -d ./tests/${PROJECT} ]; then
      if [ "${ENV}" = "docker" ]; then
        docker-compose -f ./${PROJECT}/docker-compose.yml exec web py.test -rapP ./${PROJECT} ./tests/${PROJECT} --verbose --cov-report= --cov=${PROJECT} ;
      elif [ "${PROJECT}" = "interop" ]; then
        PYTHONPATH=. py.test -rapP ./server ./idaplugin ./tests/${PROJECT} --verbose --cov-report= --cov=server --cov=idaplugin ;
      else
        PYTHONPATH=. py.test -rapP ./${PROJECT} ./tests/${PROJECT} --verbose --cov-report= --cov=${PROJECT} ;
      fi ;
    fi ;
  - if [ "${PROJECT}" = "setup.py" ]; then python ./setup.py server install ; fi ;
  - if [ "${PROJECT}" = "setup.py" ]; then python ./setup.py idaplugin install ; fi ;
  - if [ "${PROJECT}" = "docs" ]; then sphinx-build ./docs/ ./docs/_build -a -E -n -W ; fi ;

after_script:
  - if [ -d ./tests/${PROJECT} ] && [ "${ENV}" != "docker" ]; then
      coveralls ;
    fi ;
  - if [ -d ./tests/${PROJECT} ] && [ "${ENV}" = "docker" ]; then
      docker-compose -f ./${PROJECT}/docker-compose.yml exec web env TRAVIS=${TRAVIS} TRAVIS_JOB_ID=${TRAVIS_JOB_ID} TRAVIS_BRANCH=${TRAVIS_BRANCH} TRAVIS_PULL_REQUEST=${TRAVIS_PULL_REQUEST} coveralls ;
    fi ;
