version: '2'
services:

  rabbitmq:
    image: "rabbitmq:3-management"
    hostname: rabbit
    environment:
      - RABBITMQ_DEFAULT_USER=admin
      - RABBITMQ_DEFAULT_PASS=mypass
    ports:
      - "15672:15672"
      - "5672:5672"
    expose:
      - 5672
      - 15672
    depends_on:
      - db
    restart: always 

  db:
    image: mysql
    hostname: db
    environment:
      - MYSQL_USER=root
      - MYSQL_ROOT_PASSWORD=qwe123
      - MYSQL_DATABASE=rematch
      - MYSQL_REMATCH_HOST=db_1
      - MYSQL_REMATCH_PORT=3306
    ports:
      - "3306:3306"
    expose:
     - 3306
    restart: always 

  web:
    image: django
    hostname: web
    build: .
    command: bash -c "/rematch_server/start_server.sh"
    volumes:
      - /home/deb/rematch/server/
    ports:
      - "8000:8000"
    expose: 
      - "8000"
    environment:
      IN_DOCKER: 1
      USERNAME: "magic"
      PASSWORD: "qwe123QWE!@#"
      EMAIL: "admin@remat.ch"
    links:
      - db
      - rabbitmq
    depends_on:
      - db
      - rabbitmq
    restart: always 
